package model

import "time"

type TrustReport struct {
	ID              int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site            string    `gorm:"not null;column:site" json:"site"`
	SubjectKind     string    `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID       string    `gorm:"not null;column:subject_id" json:"subject_id"`
	ReporterID      int64     `gorm:"not null;column:reporter_id" json:"reporter_id"`
	ReasonID        int64     `gorm:"not null;type:bigint;column:reason_id" json:"reason_id"`
	Note            *string   `gorm:"column:note" json:"note"`
	SubjectSnapshot *string   `gorm:"column:subject_snapshot" json:"subject_snapshot"`
	SubjectURL      *string   `gorm:"column:subject_url" json:"subject_url"`
	SubjectAuthorID *int64    `gorm:"column:subject_author_id" json:"subject_author_id"`
	Weight          float32   `gorm:"type:real;not null;column:weight" json:"weight"`
	ReviewItemID    *int64    `gorm:"column:review_item_id" json:"review_item_id"`
	Status          int16     `gorm:"not null;column:status" json:"status"`
	CreatedAt       time.Time `gorm:"not null;column:created_at" json:"created_at"`

	Reason *TrustReportReason `gorm:"foreignKey:ReasonID" json:"reason,omitempty"`
}

func (TrustReport) TableName() string { return "trust_report" }

type TrustReviewItem struct {
	ID              int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site            string     `gorm:"not null;column:site" json:"site"`
	SubjectKind     string     `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID       string     `gorm:"not null;column:subject_id" json:"subject_id"`
	SubjectAuthorID *int64     `gorm:"column:subject_author_id" json:"subject_author_id"`
	Source          int16      `gorm:"not null;column:source" json:"source"`
	Severity        *int16     `gorm:"column:severity" json:"severity"`
	ClassifierScore *float32   `gorm:"type:real;column:classifier_score" json:"classifier_score"`
	ReportWeightSum *float32   `gorm:"type:real;column:report_weight_sum" json:"report_weight_sum"`
	SubjectReach    *int64     `gorm:"column:subject_reach" json:"subject_reach"`
	Priority        float32    `gorm:"type:real;not null;column:priority" json:"priority"`
	ContextNote     *string    `gorm:"column:context_note" json:"context_note"`
	Status          int16      `gorm:"not null;column:status" json:"status"`
	ClaimedBy       *int64     `gorm:"column:claimed_by" json:"claimed_by"`
	ClaimedAt       *time.Time `gorm:"column:claimed_at" json:"claimed_at"`
	DecidedBy       *int64     `gorm:"column:decided_by" json:"decided_by"`
	DecidedAt       *time.Time `gorm:"column:decided_at" json:"decided_at"`
	CreatedAt       time.Time  `gorm:"not null;column:created_at" json:"created_at"`
}

func (TrustReviewItem) TableName() string { return "trust_review_item" }
