package model

import (
	"time"

	"gorm.io/datatypes"
)

type TrustScanResult struct {
	ID             int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site           string         `gorm:"not null;column:site" json:"site"`
	SubjectKind    string         `gorm:"not null;column:subject_kind" json:"subject_kind"`
	SubjectID      string         `gorm:"not null;column:subject_id" json:"subject_id"`
	AuthorID       *int64         `gorm:"column:author_id" json:"author_id"`
	SubjectReach   *int64         `gorm:"column:subject_reach" json:"subject_reach"`
	ContentText    string         `gorm:"not null;column:content_text" json:"-"`
	Status         int16          `gorm:"not null;column:status" json:"status"`
	Flagged        *bool          `gorm:"column:flagged" json:"flagged"`
	GatewayFlagged *bool          `gorm:"column:gateway_flagged" json:"gateway_flagged"`
	Score          *float32       `gorm:"type:real;column:score" json:"score"`
	Categories     datatypes.JSON `gorm:"type:jsonb;column:categories" json:"categories,omitempty"`
	Channel        string         `gorm:"not null;default:'';column:channel" json:"channel"`
	Mode           int16          `gorm:"not null;column:mode" json:"mode"`
	CreatedAt      time.Time      `gorm:"not null;default:now();column:created_at" json:"created_at"`
	ScoredAt       *time.Time     `gorm:"column:scored_at" json:"scored_at"`
	Tier0Matched   datatypes.JSON `gorm:"type:jsonb;column:tier0_matched" json:"tier0_matched,omitempty"`
	DegradedReason *int16         `gorm:"column:degraded_reason" json:"degraded_reason"`
	ScanAttempts   int16          `gorm:"not null;default:0;column:scan_attempts" json:"scan_attempts"`
}

func (TrustScanResult) TableName() string { return "trust_scan_result" }
