package model

import "time"

type TrustTerm struct {
	ID           int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site         *string   `gorm:"column:site" json:"site"`
	TermNorm     string    `gorm:"not null;column:term_norm" json:"term_norm"`
	Kind         int16     `gorm:"not null;column:kind" json:"kind"`
	Purpose      int16     `gorm:"not null;column:purpose" json:"purpose"`
	Note         *string   `gorm:"column:note" json:"note,omitempty"`
	IsDeprecated bool      `gorm:"not null;default:false;column:is_deprecated" json:"is_deprecated"`
	CreatedAt    time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (TrustTerm) TableName() string { return "trust_term" }
