package model

import (
	"time"

	"gorm.io/datatypes"
)

const (
	KindDirect = "direct"
	KindGroup  = "group"

	RoleOwner  = "owner"
	RoleAdmin  = "admin"
	RoleMember = "member"

	MessageKindMessage = "message"
	MessageKindService = "service"

	AllowAll       = "all"
	AllowFollowing = "following"
	AllowNone      = "none"
)

type ChatUser struct {
	UserID            int64     `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	LastUpdateSeq     int64     `gorm:"not null;column:last_update_seq" json:"last_update_seq"`
	AllowIncoming     string    `gorm:"not null;check:chk_chat_user_allow_incoming,allow_incoming IN ('all','following','none');column:allow_incoming" json:"allow_incoming"`
	AcceptRequests    bool      `gorm:"not null;column:accept_requests" json:"accept_requests"`
	AllowGroupInvites string    `gorm:"not null;check:chk_chat_user_allow_group_invites,allow_group_invites IN ('all','following','none');column:allow_group_invites" json:"allow_group_invites"`
	CreatedAt         time.Time `gorm:"not null;column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"not null;column:updated_at" json:"updated_at"`
}

func (ChatUser) TableName() string { return "chat_user" }

type ChatConversation struct {
	ID               int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Kind             string     `gorm:"not null;check:chk_chat_conversation_kind,kind IN ('direct','group');column:kind" json:"kind"`
	DirectUserLowID  *int64     `gorm:"check:chk_chat_conversation_direct_users,(kind = 'direct') = (direct_user_low_id IS NOT NULL AND direct_user_high_id IS NOT NULL);column:direct_user_low_id" json:"direct_user_low_id"`
	DirectUserHighID *int64     `gorm:"check:chk_chat_conversation_direct_order,direct_user_low_id <= direct_user_high_id;column:direct_user_high_id" json:"direct_user_high_id"`
	Title            *string    `gorm:"column:title" json:"title"`
	About            *string    `gorm:"column:about" json:"about"`
	PhotoImageHash   *string    `gorm:"column:photo_image_hash" json:"photo_image_hash"`
	CreatorID        int64      `gorm:"not null;column:creator_id" json:"creator_id"`
	OriginSite       string     `gorm:"not null;column:origin_site" json:"origin_site"`
	LastSeq          int64      `gorm:"not null;column:last_seq" json:"last_seq"`
	MemberCount      int32      `gorm:"not null;column:member_count" json:"member_count"`
	CreatedAt        time.Time  `gorm:"not null;column:created_at" json:"created_at"`
	UpdatedAt        time.Time  `gorm:"not null;column:updated_at" json:"updated_at"`
	DeletedAt        *time.Time `gorm:"column:deleted_at" json:"deleted_at"`
}

func (ChatConversation) TableName() string { return "chat_conversation" }

type ChatMember struct {
	ConversationID    int64          `gorm:"primaryKey;autoIncrement:false;column:conversation_id" json:"conversation_id"`
	UserID            int64          `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	Role              string         `gorm:"not null;check:chk_chat_member_role,role IN ('owner','admin','member');column:role" json:"role"`
	JoinedAt          time.Time      `gorm:"not null;column:joined_at" json:"joined_at"`
	VisibleFromSeq    int64          `gorm:"not null;column:visible_from_seq" json:"visible_from_seq"`
	LeftAt            *time.Time     `gorm:"column:left_at" json:"left_at"`
	AcceptedAt        *time.Time     `gorm:"column:accepted_at" json:"accepted_at"`
	LastReadSeq       int64          `gorm:"not null;column:last_read_seq" json:"last_read_seq"`
	UnreadCount       int32          `gorm:"not null;column:unread_count" json:"unread_count"`
	MarkedUnread      bool           `gorm:"not null;column:marked_unread" json:"marked_unread"`
	ClearedThroughSeq int64          `gorm:"not null;column:cleared_through_seq" json:"cleared_through_seq"`
	LastMessageAt     *time.Time     `gorm:"column:last_message_at" json:"last_message_at"`
	MutedUntil        *time.Time     `gorm:"column:muted_until" json:"muted_until"`
	ArchivedAt        *time.Time     `gorm:"column:archived_at" json:"archived_at"`
	PinnedRank        *int16         `gorm:"column:pinned_rank" json:"pinned_rank"`
	Draft             datatypes.JSON `gorm:"type:jsonb;column:draft" json:"draft"`
	UpdatedAt         time.Time      `gorm:"not null;column:updated_at" json:"updated_at"`

	Conversation *ChatConversation `gorm:"foreignKey:ConversationID;constraint:OnDelete:CASCADE" json:"-"`
}

func (ChatMember) TableName() string { return "chat_member" }

type ChatMessage struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ConversationID  int64          `gorm:"not null;uniqueIndex:uq_chat_message_seq,priority:1;column:conversation_id" json:"conversation_id"`
	Seq             int64          `gorm:"not null;uniqueIndex:uq_chat_message_seq,priority:2;column:seq" json:"seq"`
	SenderID        int64          `gorm:"not null;uniqueIndex:uq_chat_message_client,priority:1;index:idx_chat_message_sender;column:sender_id" json:"sender_id"`
	Kind            string         `gorm:"not null;check:chk_chat_message_kind,kind IN ('message','service');column:kind" json:"kind"`
	Text            string         `gorm:"not null;column:text" json:"text"`
	Entities        datatypes.JSON `gorm:"type:jsonb;column:entities" json:"entities"`
	Media           datatypes.JSON `gorm:"type:jsonb;column:media" json:"media"`
	MediaGroupID    *int64         `gorm:"column:media_group_id" json:"media_group_id"`
	ReplyToSeq      *int64         `gorm:"column:reply_to_seq" json:"reply_to_seq"`
	ReplyQuote      datatypes.JSON `gorm:"type:jsonb;column:reply_quote" json:"reply_quote"`
	ForwardOrigin   datatypes.JSON `gorm:"type:jsonb;column:forward_origin" json:"forward_origin"`
	ServiceAction   datatypes.JSON `gorm:"type:jsonb;check:chk_chat_message_service,(kind = 'service') = (service_action IS NOT NULL);column:service_action" json:"service_action"`
	Context         datatypes.JSON `gorm:"type:jsonb;column:context" json:"context"`
	ClientMessageID *string        `gorm:"type:uuid;uniqueIndex:uq_chat_message_client,priority:2;column:client_message_id" json:"client_message_id"`
	OriginSite      string         `gorm:"not null;column:origin_site" json:"origin_site"`
	Silent          bool           `gorm:"not null;column:silent" json:"silent"`
	PinnedAt        *time.Time     `gorm:"column:pinned_at" json:"pinned_at"`
	EditedAt        *time.Time     `gorm:"column:edited_at" json:"edited_at"`
	DeletedAt       *time.Time     `gorm:"check:chk_chat_message_deleted_empty,deleted_at IS NULL OR (text = '' AND entities IS NULL AND media IS NULL AND reply_quote IS NULL AND context IS NULL);column:deleted_at" json:"deleted_at"`
	CreatedAt       time.Time      `gorm:"not null;column:created_at" json:"created_at"`

	Conversation *ChatConversation `gorm:"foreignKey:ConversationID;constraint:OnDelete:CASCADE" json:"-"`
}

func (ChatMessage) TableName() string { return "chat_message" }

type ChatReaction struct {
	MessageID int64     `gorm:"primaryKey;autoIncrement:false;column:message_id" json:"message_id"`
	UserID    int64     `gorm:"primaryKey;autoIncrement:false;index:idx_chat_reaction_user;column:user_id" json:"user_id"`
	Reaction  string    `gorm:"primaryKey;column:reaction" json:"reaction"`
	CreatedAt time.Time `gorm:"not null;column:created_at" json:"created_at"`

	Message *ChatMessage `gorm:"foreignKey:MessageID;constraint:OnDelete:CASCADE" json:"-"`
}

func (ChatReaction) TableName() string { return "chat_reaction" }

type ChatHiddenMessage struct {
	UserID    int64     `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	MessageID int64     `gorm:"primaryKey;autoIncrement:false;column:message_id" json:"message_id"`
	CreatedAt time.Time `gorm:"not null;column:created_at" json:"created_at"`

	Message *ChatMessage `gorm:"foreignKey:MessageID;constraint:OnDelete:CASCADE" json:"-"`
}

func (ChatHiddenMessage) TableName() string { return "chat_hidden_message" }

const (
	UpdateNewMessage       = "new_message"
	UpdateEditMessage      = "edit_message"
	UpdateDeleteMessages   = "delete_messages"
	UpdateReadInbox        = "read_inbox"
	UpdateReadOutbox       = "read_outbox"
	UpdateMessageReactions = "message_reactions"
	UpdatePinnedMessages   = "pinned_messages"
	UpdateDialog           = "dialog"
	UpdateHideMessages     = "hide_messages"
	UpdateClearHistory     = "clear_history"
	UpdateMember           = "member"
	UpdateConversation     = "conversation"
)

type ChatUpdate struct {
	UserID         int64          `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	UpdateSeq      int64          `gorm:"primaryKey;autoIncrement:false;column:update_seq" json:"update_seq"`
	Kind           string         `gorm:"not null;check:chk_chat_update_kind,kind IN ('new_message','edit_message','delete_messages','read_inbox','read_outbox','message_reactions','pinned_messages','dialog','hide_messages','clear_history','member','conversation');column:kind" json:"kind"`
	ConversationID int64          `gorm:"not null;column:conversation_id" json:"conversation_id"`
	Data           datatypes.JSON `gorm:"type:jsonb;not null;column:data" json:"data"`
	CreatedAt      time.Time      `gorm:"not null;index:idx_chat_update_created;column:created_at" json:"created_at"`
}

func (ChatUpdate) TableName() string { return "chat_update" }

const (
	ReportPending   = "pending"
	ReportForwarded = "forwarded"
	ReportFailed    = "failed"
)

const (
	ResolutionRemoved   = "removed"
	ResolutionDismissed = "dismissed"
)

type ChatReport struct {
	ID                 int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	MessageID          int64          `gorm:"not null;uniqueIndex:uq_chat_report,priority:2;column:message_id" json:"message_id"`
	ConversationID     int64          `gorm:"not null;column:conversation_id" json:"conversation_id"`
	ReporterID         int64          `gorm:"not null;uniqueIndex:uq_chat_report,priority:1;column:reporter_id" json:"reporter_id"`
	ReportedUserID     int64          `gorm:"not null;column:reported_user_id" json:"reported_user_id"`
	Reason             string         `gorm:"not null;column:reason" json:"reason"`
	Note               *string        `gorm:"column:note" json:"note"`
	Snapshot           datatypes.JSON `gorm:"type:jsonb;not null;column:snapshot" json:"snapshot"`
	OriginSite         string         `gorm:"not null;column:origin_site" json:"origin_site"`
	Status             string         `gorm:"not null;check:chk_chat_report_status,status IN ('pending','forwarded','failed');column:status" json:"status"`
	TrustReviewItemID  *int64         `gorm:"column:trust_review_item_id" json:"trust_review_item_id"`
	ForwardAttempts    int32          `gorm:"not null;column:forward_attempts" json:"forward_attempts"`
	ForwardError       *string        `gorm:"column:forward_error" json:"forward_error"`
	CreatedAt          time.Time      `gorm:"not null;column:created_at" json:"created_at"`
	ForwardedAt        *time.Time     `gorm:"column:forwarded_at" json:"forwarded_at"`
	Resolution         *string        `gorm:"check:chk_chat_report_resolution,resolution IN ('removed','dismissed');column:resolution" json:"resolution"`
	TrustDispositionID *int64         `gorm:"column:trust_disposition_id" json:"trust_disposition_id"`
	ResolvedAt         *time.Time     `gorm:"column:resolved_at" json:"resolved_at"`
}

func (ChatReport) TableName() string { return "chat_report" }

// One row per message cmd/import-chat wrote; the key is the source message
// ("kungal:123", "moyu:45", "kungal:123#2" for the second photo split out of
// one old message). It makes a re-run import only what is new.
type ChatImportMessage struct {
	SourceKey      string    `gorm:"primaryKey;column:source_key" json:"source_key"`
	MessageID      int64     `gorm:"not null;column:message_id" json:"message_id"`
	ConversationID int64     `gorm:"not null;index:idx_chat_import_message_conversation;column:conversation_id" json:"conversation_id"`
	ImportedAt     time.Time `gorm:"not null;column:imported_at" json:"imported_at"`
}

func (ChatImportMessage) TableName() string { return "chat_import_message" }
