package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type CatalogCharacter struct {
	ID               int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName      string         `gorm:"not null" json:"display_name"`
	DisplayNameNorm  string         `gorm:"->;-:migration" json:"display_name_norm"`
	Latin            *string        `json:"latin"`
	Lang             string         `gorm:"not null;default:''" json:"lang"`
	Gender           *int16         `json:"gender"`
	Description      string         `gorm:"not null;default:''" json:"description"`
	InstanceOf       *int64         `gorm:"index;type:bigint" json:"instance_of"`
	ImageHash        *string        `json:"image_hash"`
	ImageSourceHash  *string        `json:"image_source_hash"`
	FigureHash       *string        `json:"figure_hash"`
	FigureSourceHash *string        `json:"figure_source_hash"`
	BirthdayMonth    *int16         `json:"birthday_month"`
	BirthdayDay      *int16         `json:"birthday_day"`
	BloodType        *int16         `json:"blood_type"`
	HeightCm         *int16         `json:"height_cm"`
	WeightKg         *int16         `json:"weight_kg"`
	BustCm           *int16         `json:"bust_cm"`
	WaistCm          *int16         `json:"waist_cm"`
	HipCm            *int16         `json:"hip_cm"`
	Cup              *string        `json:"cup"`
	Extra            datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance  datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt        time.Time      `json:"created_at"`
	UpdatedAt        time.Time      `json:"updated_at"`
	DeletedAt        gorm.DeletedAt `gorm:"index" json:"-"`

	Instance *CatalogCharacter `gorm:"foreignKey:InstanceOf" json:"instance,omitempty"`
}

func (CatalogCharacter) TableName() string { return "catalog_character" }

type CatalogCharacterAlias struct {
	ID                 int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID        int64   `gorm:"not null;type:bigint;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"character_id"`
	Name               string  `gorm:"not null;uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"name"`
	NameNorm           string  `gorm:"->;-:migration" json:"name_norm"`
	Latin              *string `json:"latin"`
	Lang               string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_alias_owner_name_lang" json:"lang"`
	Kind               int16   `gorm:"not null" json:"kind"`
	IsPrimaryForLocale bool    `gorm:"not null" json:"is_primary_for_locale"`
	SourceID           *int16  `gorm:"type:smallint" json:"source_id"`
	Provenance         int16   `gorm:"not null" json:"provenance"`
	MTModel            string  `gorm:"not null;default:''" json:"mt_model"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Source    *CatalogSource    `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCharacterAlias) TableName() string { return "catalog_character_alias" }

type CatalogCharacterIntro struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID int64     `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"character_id"`
	Lang        string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_character_intro" json:"lang"`
	Intro       string    `gorm:"type:text;not null" json:"intro"`
	SourceID    int16     `gorm:"not null;uniqueIndex:uq_catalog_character_intro" json:"source_id"`
	Provenance  int16     `gorm:"not null" json:"provenance"`
	SrcHash     string    `gorm:"not null;default:''" json:"src_hash"`
	MTModel     string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`

	Character *CatalogCharacter `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Source    *CatalogSource    `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogCharacterIntro) TableName() string { return "catalog_character_intro" }

// CatalogCharacterIntroPanelVerdict is a cache, not a record: a kept-incumbent
// panel verdict writes no intro row, so without it every panel run re-extracts
// and re-judges the same unchanged (work intro, incumbent) pair. Rows are
// re-derivable — merges delete them instead of repointing.
type CatalogCharacterIntroPanelVerdict struct {
	WorkID        int64     `gorm:"primaryKey;autoIncrement:false" json:"work_id"`
	CharacterID   int64     `gorm:"primaryKey;autoIncrement:false" json:"character_id"`
	SrcHash       string    `gorm:"not null" json:"src_hash"`
	IncumbentHash string    `gorm:"not null" json:"incumbent_hash"`
	JudgedAt      time.Time `gorm:"not null" json:"judged_at"`
}

func (CatalogCharacterIntroPanelVerdict) TableName() string {
	return "catalog_character_intro_panel_verdict"
}

type CatalogCharacterTrait struct {
	ID                      int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	VndbTID                 string    `gorm:"column:vndb_tid;not null;uniqueIndex:uq_catalog_character_trait_vndb_tid" json:"vndb_tid"`
	Name                    string    `gorm:"not null" json:"name"`
	NameZh                  string    `gorm:"column:name_zh;not null;default:''" json:"name_zh"`
	NameZhProvenance        int16     `gorm:"column:name_zh_provenance;not null;default:0" json:"name_zh_provenance"`
	GroupTID                string    `gorm:"column:group_tid;not null" json:"group_tid"`
	GOrder                  int16     `gorm:"column:gorder;not null" json:"gorder"`
	DefaultSpoil            int16     `gorm:"column:default_spoil;not null" json:"default_spoil"`
	Sexual                  bool      `gorm:"not null" json:"sexual"`
	SexualFamily            bool      `gorm:"column:sexual_family;not null;default:false" json:"sexual_family"`
	Searchable              bool      `gorm:"not null" json:"searchable"`
	Applicable              bool      `gorm:"not null" json:"applicable"`
	Alias                   string    `gorm:"type:text;not null" json:"alias"`
	Description             string    `gorm:"type:text;not null" json:"description"`
	DescriptionZh           string    `gorm:"column:description_zh;type:text;not null;default:''" json:"description_zh"`
	DescriptionZhSourceHash string    `gorm:"column:description_zh_source_hash;type:text;not null;default:''" json:"description_zh_source_hash"`
	CreatedAt               time.Time `json:"created_at"`
	UpdatedAt               time.Time `json:"updated_at"`
}

func (CatalogCharacterTrait) TableName() string { return "catalog_character_trait" }

type CatalogCharacterTraitParent struct {
	TraitID  int64 `gorm:"primaryKey;autoIncrement:false" json:"trait_id"`
	ParentID int64 `gorm:"primaryKey;autoIncrement:false" json:"parent_id"`

	Trait  *CatalogCharacterTrait `gorm:"foreignKey:TraitID" json:"trait,omitempty"`
	Parent *CatalogCharacterTrait `gorm:"foreignKey:ParentID" json:"parent,omitempty"`
}

func (CatalogCharacterTraitParent) TableName() string { return "catalog_character_trait_parent" }

type CatalogCharacterTraitLink struct {
	ID           int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	CharacterID  int64     `gorm:"not null;uniqueIndex:uq_catalog_character_trait_link,priority:1" json:"character_id"`
	TraitID      int64     `gorm:"not null;uniqueIndex:uq_catalog_character_trait_link,priority:2" json:"trait_id"`
	SpoilerLevel int16     `gorm:"not null" json:"spoiler_level"`
	Lie          bool      `gorm:"not null" json:"lie"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`

	Character *CatalogCharacter      `gorm:"foreignKey:CharacterID" json:"character,omitempty"`
	Trait     *CatalogCharacterTrait `gorm:"foreignKey:TraitID" json:"trait,omitempty"`
}

func (CatalogCharacterTraitLink) TableName() string { return "catalog_character_trait_link" }
