package model

import (
	"time"

	"gorm.io/datatypes"
)

type CatalogEngine struct {
	ID          int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Name        string         `gorm:"type:text;not null;uniqueIndex" json:"name"`
	Description string         `gorm:"type:text;not null" json:"description"`
	Aliases     datatypes.JSON `gorm:"type:jsonb;not null" json:"aliases"`
	CreatedAt   time.Time      `json:"created_at"`
	UpdatedAt   time.Time      `json:"updated_at"`
}

func (CatalogEngine) TableName() string { return "catalog_engine" }

type CatalogWorkEngine struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_engine,priority:1" json:"work_id"`
	EngineID  int64     `gorm:"not null;index;uniqueIndex:uq_catalog_work_engine,priority:2" json:"engine_id"`
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Engine *CatalogEngine `gorm:"foreignKey:EngineID" json:"engine,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkEngine) TableName() string { return "catalog_work_engine" }
