package model

import "time"

const EntityFollowsPerUserMax = 1000

type CatalogUserEntityFollow struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ActorUID   int64     `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_user_entity_follow,priority:1" json:"actor_uid"`
	EntityType int16     `gorm:"not null;uniqueIndex:uq_catalog_user_entity_follow,priority:2;index:idx_catalog_user_entity_follow_entity,priority:1" json:"entity_type"`
	EntityID   int64     `gorm:"not null;uniqueIndex:uq_catalog_user_entity_follow,priority:3;index:idx_catalog_user_entity_follow_entity,priority:2" json:"entity_id"`
	ClientID   string    `gorm:"not null" json:"client_id"`
	Site       string    `gorm:"not null;default:''" json:"site"`
	CreatedAt  time.Time `json:"created_at"`
}

func (CatalogUserEntityFollow) TableName() string { return "catalog_user_entity_follow" }
