package model

import "time"

const (
	FolderVisibilityPrivate int16 = 0
	FolderVisibilityPublic  int16 = 1
)

const (
	FolderNameMax        = 100
	FolderDescriptionMax = 500
	FoldersPerUserMax    = 200
	FolderItemsMax       = 10_000
)

type CatalogUserFolder struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	OwnerUID    int64     `gorm:"column:owner_uid;not null;index" json:"owner_uid"`
	Name        string    `gorm:"not null;size:100" json:"name"`
	Description string    `gorm:"size:500" json:"description"`
	Visibility  int16     `gorm:"not null;default:0" json:"visibility"`
	IsDefault   bool      `gorm:"not null;default:false" json:"is_default"`
	ItemCount   int       `gorm:"not null;default:0" json:"item_count"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (CatalogUserFolder) TableName() string { return "catalog_user_folder" }

type CatalogUserFolderItem struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	FolderID  int64     `gorm:"not null;uniqueIndex:uq_catalog_user_folder_item,priority:1" json:"folder_id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_user_folder_item,priority:2;index" json:"work_id"`
	OwnerUID  int64     `gorm:"column:owner_uid;not null;index:idx_catalog_user_folder_item_sync,priority:1" json:"owner_uid"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `gorm:"index:idx_catalog_user_folder_item_sync,priority:2" json:"updated_at"`
}

func (CatalogUserFolderItem) TableName() string { return "catalog_user_folder_item" }
