package model

import "time"

const PlaytimeMinutesMax = 60_000

const PlaytimeMinutesMin = 10

const PlaytimeMinReporters = 3

type CatalogUserPlaytime struct {
	ID           int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ActorUID     int64      `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_user_playtime,priority:1;index:idx_catalog_user_playtime_sync,priority:1" json:"actor_uid"`
	WorkID       int64      `gorm:"not null;uniqueIndex:uq_catalog_user_playtime,priority:2;index" json:"work_id"`
	ClientID     string     `gorm:"not null;uniqueIndex:uq_catalog_user_playtime,priority:3" json:"client_id"`
	Minutes      int        `gorm:"not null" json:"minutes"`
	LastPlayedAt *time.Time `json:"last_played_at"`
	CreatedAt    time.Time  `json:"created_at"`
	UpdatedAt    time.Time  `gorm:"index:idx_catalog_user_playtime_sync,priority:2" json:"updated_at"`
}

func (CatalogUserPlaytime) TableName() string { return "catalog_user_playtime" }
