package model

import (
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

type CatalogWork struct {
	ID            int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	MediumID      int16   `gorm:"not null;uniqueIndex:uq_catalog_work_claim;index:idx_catalog_work_medium_status,priority:1" json:"medium_id"`
	Site          *string `gorm:"uniqueIndex:uq_catalog_work_claim" json:"site"`
	ProductWorkID *int64  `gorm:"uniqueIndex:uq_catalog_work_claim" json:"product_work_id"`
	OwnerUserID   *int64  `gorm:"column:owner_user_id;index" json:"owner_user_id"`
	ClaimState    *int16  `gorm:"column:claim_state" json:"claim_state"`
	OLang         string  `gorm:"column:olang;not null" json:"olang"`
	DisplayName   string  `gorm:"not null" json:"display_name"`
	ContentRating int16   `gorm:"not null" json:"content_rating"`
	Status        int16   `gorm:"not null;index:idx_catalog_work_medium_status,priority:2" json:"status"`
	DisplayNSFW   bool    `gorm:"column:display_nsfw;not null" json:"display_nsfw"`
	// CoverArtAllExplicit is derived from catalog_work_cover by a trigger and
	// is read-only here for the same reason the *_norm columns are: a Save()
	// carrying a stale struct would silently overwrite the database's own
	// answer and put the work back on the sfw shelf with no safe cover to show.
	CoverArtAllExplicit bool           `gorm:"->;-:migration;column:cover_art_all_explicit" json:"cover_art_all_explicit"`
	Extra               datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance     datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"field_provenance"`
	CreatedAt           time.Time      `json:"created_at"`
	UpdatedAt           time.Time      `json:"updated_at"`
	DeletedAt           gorm.DeletedAt `gorm:"index" json:"-"`

	Medium *CatalogMedium `gorm:"foreignKey:MediumID" json:"medium,omitempty"`
}

func (CatalogWork) TableName() string { return "catalog_work" }

type CatalogWorkTitle struct {
	ID         int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID     int64   `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"work_id"`
	Lang       string  `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_title" json:"lang"`
	Title      string  `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"title"`
	TitleNorm  string  `gorm:"->;-:migration" json:"title_norm"`
	Latin      *string `json:"latin"`
	Kind       int16   `gorm:"not null;uniqueIndex:uq_catalog_work_title" json:"kind"`
	Provenance int16   `gorm:"not null" json:"provenance"`
	SrcHash    *string `json:"src_hash"`
	MTModel    *string `json:"mt_model"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogWorkTitle) TableName() string { return "catalog_work_title" }

type CatalogWorkIntro struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID     int64     `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"work_id"`
	Lang       string    `gorm:"not null;default:'';uniqueIndex:uq_catalog_work_intro" json:"lang"`
	Intro      string    `gorm:"type:text;not null" json:"intro"`
	SourceID   int16     `gorm:"not null;uniqueIndex:uq_catalog_work_intro" json:"source_id"`
	Provenance int16     `gorm:"not null" json:"provenance"`
	SrcHash    string    `gorm:"not null;default:''" json:"src_hash"`
	MTModel    string    `gorm:"not null;default:''" json:"mt_model"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkIntro) TableName() string { return "catalog_work_intro" }

type CatalogWorkCover struct {
	ID             int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID         int64     `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"work_id"`
	ImageHash      string    `gorm:"not null;uniqueIndex:uq_catalog_work_cover" json:"image_hash"`
	SortOrder      int       `gorm:"not null;default:0" json:"sort_order"`
	Kind           string    `gorm:"not null;default:''" json:"kind"`
	PortraitPinned bool      `gorm:"not null;default:false" json:"portrait_pinned"`
	Sexual         int16     `gorm:"not null;default:0" json:"sexual"`
	Violence       int16     `gorm:"not null;default:0" json:"violence"`
	SourceID       int16     `gorm:"not null" json:"source_id"`
	CreatedAt      time.Time `json:"created_at"`
	UpdatedAt      time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkCover) TableName() string { return "catalog_work_cover" }

type CatalogWorkScreenshot struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"work_id"`
	ImageHash string    `gorm:"not null;uniqueIndex:uq_catalog_work_screenshot" json:"image_hash"`
	SortOrder int       `gorm:"not null;default:0" json:"sort_order"`
	Caption   string    `gorm:"type:text;not null;default:''" json:"caption"`
	Sexual    int16     `gorm:"not null;default:0" json:"sexual"`
	Violence  int16     `gorm:"not null;default:0" json:"violence"`
	SourceID  int16     `gorm:"not null" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkScreenshot) TableName() string { return "catalog_work_screenshot" }

type CatalogWorkRating struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"work_id"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_rating" json:"source_id"`
	Score     float64   `gorm:"type:numeric;not null" json:"score"`
	VoteCount int       `gorm:"not null;default:0" json:"vote_count"`
	Rank      *int      `json:"rank"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	// Distribution holds a bucket histogram keyed by the source's own scale;
	// Stats holds the spread of the same population. Every source now fills
	// Distribution, but from three different bases, and only two of them add up
	// to the vote_count sitting next to them. Bangumi and DLsite publish the
	// histogram with the aggregate (score_details / rate_count_detail), so those
	// agree by construction. ErogameScape publishes none: its bars are computed
	// from the mirror's `reviews` table, which syncs on a different cursor than
	// the `games` row the median, vote_count and Stats spread all come from —
	// deliberately mismatched, documented in the contract, never reconciled.
	// VNDB publishes no histogram in the database dump either, but does publish
	// a separate votes dump (staged as src_vndb.vn_vote_stats); it omits votes
	// from private lists, so those bars sum to at most c_votecount. VNDB's Stats
	// carries only `average` — c_average, the plain mean beside the smoothed
	// c_rating that Score holds. HowLongToBeat publishes the histogram with the
	// aggregate (userReviews, 5-point buckets on the 0-100 scale), so like
	// Bangumi and DLsite its bars agree with vote_count by construction.
	Distribution datatypes.JSON `gorm:"type:jsonb" json:"distribution,omitempty"`
	Stats        datatypes.JSON `gorm:"type:jsonb" json:"stats,omitempty"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkRating) TableName() string { return "catalog_work_rating" }

type CatalogWorkTag struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_tag" json:"work_id"`
	Name      string    `gorm:"type:text;not null;uniqueIndex:uq_catalog_work_tag" json:"name"`
	Count     int       `gorm:"not null;default:0" json:"count"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_tag" json:"source_id"`
	Spoiler   int16     `gorm:"not null" json:"spoiler"`
	Sexual    bool      `gorm:"not null" json:"sexual"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkTag) TableName() string { return "catalog_work_tag" }

type CatalogWorkPopularity struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"work_id"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"source_id"`
	Metric    int16     `gorm:"not null;uniqueIndex:uq_catalog_work_popularity" json:"metric"`
	Value     int64     `gorm:"not null" json:"value"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPopularity) TableName() string { return "catalog_work_popularity" }

type CatalogWorkPlaytime struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_playtime" json:"work_id"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_playtime" json:"source_id"`
	Minutes   int       `gorm:"not null" json:"minutes"`
	VoteCount int       `gorm:"not null;default:0" json:"vote_count"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPlaytime) TableName() string { return "catalog_work_playtime" }

type CatalogRelease struct {
	ID              int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID          int64          `gorm:"not null;index" json:"work_id"`
	Kind            int16          `gorm:"not null" json:"kind"`
	Title           *string        `json:"title"`
	Lang            *string        `json:"lang"`
	Platform        *string        `json:"platform"`
	ReleasedY       *int16         `json:"released_y"`
	ReleasedM       *int16         `json:"released_m"`
	ReleasedD       *int16         `json:"released_d"`
	EventID         *int64         `json:"event_id"`
	Extra           datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"extra"`
	FieldProvenance datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"-"`
	CreatedAt       time.Time      `json:"created_at"`
	DeletedAt       gorm.DeletedAt `gorm:"index" json:"-"`

	Work *CatalogWork `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogRelease) TableName() string { return "catalog_release" }

type CatalogSeries struct {
	ID          int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	DisplayName string    `gorm:"not null" json:"display_name"`
	SourceID    int16     `gorm:"not null;uniqueIndex:uq_catalog_series_source,priority:1" json:"source_id"`
	ExternalID  string    `gorm:"not null;uniqueIndex:uq_catalog_series_source,priority:2" json:"external_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`

	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogSeries) TableName() string { return "catalog_series" }

type CatalogSeriesMember struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SeriesID  int64     `gorm:"not null;uniqueIndex:uq_catalog_series_member,priority:1" json:"series_id"`
	WorkID    int64     `gorm:"not null;index;uniqueIndex:uq_catalog_series_member,priority:2" json:"work_id"`
	Position  int16     `gorm:"not null;default:0" json:"position"`
	Kind      int16     `gorm:"not null;default:0" json:"kind"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Series *CatalogSeries `gorm:"foreignKey:SeriesID" json:"series,omitempty"`
	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
}

func (CatalogSeriesMember) TableName() string { return "catalog_series_member" }

type CatalogWorkPlatform struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID    int64     `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:1" json:"work_id"`
	Platform  string    `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:2" json:"platform"`
	SourceID  int16     `gorm:"not null;uniqueIndex:uq_catalog_work_platform,priority:3" json:"source_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	Work   *CatalogWork   `gorm:"foreignKey:WorkID" json:"work,omitempty"`
	Source *CatalogSource `gorm:"foreignKey:SourceID" json:"source,omitempty"`
}

func (CatalogWorkPlatform) TableName() string { return "catalog_work_platform" }
