package model

import "time"

const (
	WorkStateWish    int16 = 1
	WorkStateDoing   int16 = 2
	WorkStateDone    int16 = 3
	WorkStateOnHold  int16 = 4
	WorkStateDropped int16 = 5
)

const (
	WorkCompletionOneRoute int16 = 1
	WorkCompletionMain     int16 = 2
	WorkCompletionAll      int16 = 3
)

type CatalogUserWorkState struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ActorUID   int64     `gorm:"column:actor_uid;not null;uniqueIndex:uq_catalog_user_work_state,priority:1;index:idx_catalog_user_work_state_sync,priority:1" json:"actor_uid"`
	WorkID     int64     `gorm:"not null;uniqueIndex:uq_catalog_user_work_state,priority:2;index" json:"work_id"`
	State      int16     `gorm:"not null" json:"state"`
	Completion *int16    `json:"completion"`
	CreatedAt  time.Time `json:"created_at"`
	UpdatedAt  time.Time `gorm:"index:idx_catalog_user_work_state_sync,priority:2" json:"updated_at"`
}

func (CatalogUserWorkState) TableName() string { return "catalog_user_work_state" }
