package model

import (
	"crypto/sha256"
	"encoding/hex"
	"time"

	"gorm.io/datatypes"
)

// Tier0 decisions mirror the wire values of trust's POST /api/v1/trust/check.
// They are redeclared rather than imported: news is a different database and a
// different process, and importing trust's service package to reach three string
// constants would couple the two schemas for no gain.
const (
	Tier0Allow = "allow"
	Tier0Hold  = "hold"
	Tier0Deny  = "deny"
)

const (
	DegradedBudget       = "budget"
	DegradedUpstream     = "upstream"
	DegradedTransport    = "transport"
	DegradedUnconfigured = "unconfigured"
)

// ModerationAttemptCeiling caps how many verdicts one piece of text may
// accumulate. The verdict log is append-only, so counting its rows IS the
// retry counter — there is no separate circuit breaker. Once the ceiling is
// reached the item simply stays pending with its scoring marked unavailable,
// which is the correct end state: a human still decides.
const ModerationAttemptCeiling = 5

// SystemActorUID marks a decision no human made: the Tier0 auto-reject, and the
// scheduled standing release of a source the user ruled needs no review. Both
// are reversible by hand.
const SystemActorUID int64 = 0

// Fingerprint identifies the exact text a verdict judged. It lives on the model
// rather than in the grading job because the admin face also has to decide
// whether a stored verdict still describes what is on the page — two copies of
// this definition would let the queue and the console disagree about which items
// are graded. The separator is NUL so that moving a character across a field
// boundary cannot produce the same digest.
func (i NewsItem) Fingerprint() string {
	text := i.Title + "\x00" + i.Preview + "\x00" + i.Lane
	if i.Body != "" {
		// Appended only when present, so every verdict graded before bodies
		// existed still describes its item.
		text += "\x00" + i.Body
	}
	sum := sha256.Sum256([]byte(text))
	return hex.EncodeToString(sum[:])
}

// NewsModerationVerdict is one machine judgement of one version of one item.
// Append-only: an item whose text changes goes back to the queue and earns a
// NEW verdict, and the old row stays as the record of what the text looked like
// when it was published.
type NewsModerationVerdict struct {
	ID     int64 `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ItemID int64 `gorm:"not null;column:item_id" json:"item_id"`
	// ContentFingerprint answers "was THIS text judged", which no timestamp can:
	// an item's updated_at also moves when a human publishes it, so a
	// timestamp comparison would re-queue everything the moment it was decided.
	ContentFingerprint string         `gorm:"not null;column:content_fingerprint" json:"content_fingerprint"`
	Tier0Decision      string         `gorm:"not null;column:tier0_decision" json:"tier0_decision"`
	Tier0Matched       datatypes.JSON `gorm:"type:jsonb;column:tier0_matched" json:"tier0_matched,omitempty"`
	// AIFlagged is a pointer so that "the model said it is clean" and "the model
	// never spoke" are different values in the database. Collapsing those two
	// into one false is the exact shape of the fail-open incident this track is
	// built to avoid.
	AIFlagged      *bool          `gorm:"column:ai_flagged" json:"ai_flagged"`
	AIScore        *float32       `gorm:"type:real;column:ai_score" json:"ai_score"`
	AICategories   datatypes.JSON `gorm:"type:jsonb;column:ai_categories" json:"ai_categories,omitempty"`
	AIChannel      string         `gorm:"not null;default:'';column:ai_channel" json:"ai_channel"`
	Degraded       bool           `gorm:"not null;column:degraded" json:"degraded"`
	DegradedReason string         `gorm:"not null;default:'';column:degraded_reason" json:"degraded_reason"`
	CreatedAt      time.Time      `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsModerationVerdict) TableName() string { return "news_moderation_verdict" }

// NewsModerationDecision is the audit line for every status change a human (or
// the Tier0 auto-reject) made. It is also the whole of the retraction path:
// withdrawing an item is a decision row plus a status, never a delete.
type NewsModerationDecision struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ItemID     int64     `gorm:"not null;column:item_id" json:"item_id"`
	ActorUID   int64     `gorm:"not null;column:actor_uid" json:"actor_uid"`
	FromStatus int16     `gorm:"not null;column:from_status" json:"from_status"`
	ToStatus   int16     `gorm:"not null;column:to_status" json:"to_status"`
	Reason     string    `gorm:"not null;default:'';column:reason" json:"reason"`
	CreatedAt  time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsModerationDecision) TableName() string { return "news_moderation_decision" }
