package model

import "time"

const (
	SourceKeyYmgal     = "ymgal"
	SourceKeyHihyou    = "galgame_hihyou"
	SourceKeyCommunity = "community"
)

// A lane is what the upstream calls the article's own section. 月幕 serves the
// two from separate endpoints (/open/topic/news and /open/topic/column) with an
// identical payload, so the lane is the only thing that survives to tell them
// apart downstream.
const (
	LaneNews   = "news"
	LaneColumn = "column"
)

func IsKnownLane(lane string) bool {
	return lane == LaneNews || lane == LaneColumn
}

const (
	StatusPending   int16 = 0
	StatusPublished int16 = 1
	StatusRejected  int16 = 2
	StatusWithdrawn int16 = 3
)

const (
	WorkConfidenceManual      int16 = 0
	WorkConfidenceExactAnchor int16 = 1
	WorkConfidenceHeuristic   int16 = 2
)

// PreviewMaxRunes is the hard ceiling the importers truncate to and the DB
// CHECK constraint enforces. It exists because 月幕 authorised the preview
// message and the banner only — "不要文章的全部内容" — so an unbounded text
// column would be a promise we could break by accident.
const PreviewMaxRunes = 200

// BodyMaxRunes bounds an original community submission. Only the community
// source may carry a body; the partners granted a preview and a link.
const BodyMaxRunes = 20000

type NewsSource struct {
	Key          string `gorm:"primaryKey;column:key" json:"key"`
	DisplayName  string `gorm:"not null;column:display_name" json:"display_name"`
	HomepageURL  string `gorm:"not null;column:homepage_url" json:"homepage_url"`
	Attribution  string `gorm:"not null;column:attribution" json:"attribution"`
	PublisherUID int64  `gorm:"not null;column:publisher_uid" json:"publisher_uid"`
	ColumnURL    string `gorm:"not null;default:'';column:column_url" json:"column_url"`
	Active       bool   `gorm:"not null;column:active" json:"active"`
	// AutoPublish marks a source the user ruled needs no review: its imports and
	// its publisher's own submissions go out without the console.
	AutoPublish bool      `gorm:"not null;default:false;column:auto_publish" json:"auto_publish"`
	CreatedAt   time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"not null;default:now();column:updated_at" json:"updated_at"`
}

func (NewsSource) TableName() string { return "news_source" }

type NewsItem struct {
	ID         int64  `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SourceKey  string `gorm:"not null;column:source_key" json:"source_key"`
	Lane       string `gorm:"not null;column:lane" json:"lane"`
	ExternalID string `gorm:"not null;column:external_id" json:"external_id"`
	Title      string `gorm:"not null;column:title" json:"title"`
	Preview    string `gorm:"not null;column:preview" json:"preview"`
	// UpstreamCategory is the partner's own section label (月幕 sends 资讯 for the
	// news lane and 感想评测 / 技术教程 / 杂谈 / 翻译 for the column lane). It is
	// operator-facing only — the moderation queue needs it to triage, and the
	// public face deliberately does not expose partner-internal vocabulary.
	UpstreamCategory string `gorm:"not null;column:upstream_category" json:"upstream_category"`
	SourceURL        string `gorm:"not null;column:source_url" json:"source_url"`
	BannerHash       string `gorm:"not null;default:'';column:banner_hash" json:"banner_hash"`
	// BannerOriginURL is where the banner bytes came from. Without it there is no
	// way to tell "the partner swapped the picture" from "we already have it", and
	// a poll running every ten minutes would have to choose between re-downloading
	// every banner forever and never noticing a replacement.
	BannerOriginURL string    `gorm:"not null;column:banner_origin_url" json:"banner_origin_url"`
	PublishedAt     time.Time `gorm:"not null;column:published_at" json:"published_at"`
	Status          int16     `gorm:"not null;column:status" json:"status"`
	// SubmitterUID is the account that wrote the item through /v2/me/news; NULL
	// for rows an importer wrote.
	SubmitterUID *int64     `gorm:"column:submitter_uid" json:"submitter_uid,omitempty"`
	Body         string     `gorm:"not null;default:'';column:body" json:"body"`
	FirstSeenAt  time.Time  `gorm:"not null;default:now();column:first_seen_at" json:"first_seen_at"`
	LastSeenAt   time.Time  `gorm:"not null;default:now();column:last_seen_at" json:"last_seen_at"`
	DeadAt       *time.Time `gorm:"column:dead_at" json:"dead_at,omitempty"`
	CreatedAt    time.Time  `gorm:"not null;default:now();column:created_at" json:"created_at"`
	UpdatedAt    time.Time  `gorm:"not null;default:now();column:updated_at" json:"updated_at"`
}

func (NewsItem) TableName() string { return "news_item" }

type NewsItemImage struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ItemID    int64     `gorm:"not null;column:item_id" json:"item_id"`
	ImageHash string    `gorm:"not null;column:image_hash" json:"image_hash"`
	OriginURL string    `gorm:"not null;column:origin_url" json:"origin_url"`
	Position  int       `gorm:"not null;default:0;type:integer;column:position" json:"position"`
	CreatedAt time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsItemImage) TableName() string { return "news_item_image" }

type NewsItemWork struct {
	ItemID     int64     `gorm:"primaryKey;column:item_id" json:"item_id"`
	WorkID     int64     `gorm:"primaryKey;column:work_id" json:"work_id"`
	Confidence int16     `gorm:"not null;column:confidence" json:"confidence"`
	CreatedAt  time.Time `gorm:"not null;default:now();column:created_at" json:"created_at"`
}

func (NewsItemWork) TableName() string { return "news_item_work" }
