package service

import (
	"testing"

	"api/internal/platform/store/model"
)

// shippedByApplication recreates the coupon tables as production held them
// between the first deploy and the re-key (pg_dump of 2026-09-19).
func shippedByApplication(t *testing.T) {
	t.Helper()
	for _, stmt := range []string{
		`DROP TABLE IF EXISTS store_coupon_shares, store_coupons`,
		`CREATE TABLE store_coupons (
			id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, batch_id bigint NOT NULL,
			face_value bigint NOT NULL, code varchar(200) NOT NULL, expires_on varchar(10),
			client_id varchar(50), delivered_at timestamptz, created_at timestamptz)`,
		`CREATE INDEX idx_store_coupons_batch_id ON store_coupons (batch_id)`,
		`CREATE INDEX idx_store_coupons_client_id ON store_coupons (client_id)`,
		`CREATE UNIQUE INDEX uq_store_coupon_code ON store_coupons (code)`,
		`CREATE TABLE store_coupon_shares (
			batch_id bigint NOT NULL, client_id varchar(50) NOT NULL, app_name varchar(100) NOT NULL,
			uniques bigint NOT NULL, share_ppm bigint NOT NULL, entitled_points bigint NOT NULL,
			allocated_points bigint NOT NULL, PRIMARY KEY (batch_id, client_id))`,
	} {
		if err := testDB.Exec(stmt).Error; err != nil {
			t.Fatalf("recreate the shipped tables: %v", err)
		}
	}
	t.Cleanup(func() {
		testDB.Exec(`DROP TABLE IF EXISTS store_coupon_shares, store_coupons`)
		if err := testDB.AutoMigrate(&model.Coupon{}, &model.CouponShare{}); err != nil {
			t.Fatalf("restore the current tables: %v", err)
		}
	})
}

func primaryKey(t *testing.T, table string) []string {
	t.Helper()
	var cols []string
	err := testDB.Raw(`
		SELECT a.attname FROM pg_index i
		  JOIN pg_attribute a ON a.attrelid = i.indrelid AND a.attnum = ANY(i.indkey)
		 WHERE i.indrelid = ?::regclass AND i.indisprimary
		 ORDER BY array_position(i.indkey::int2[], a.attnum)`, table).Scan(&cols).Error
	if err != nil {
		t.Fatalf("read the primary key of %s: %v", table, err)
	}
	return cols
}

func TestRekeyCouponsByOwnerKeepsDraftCodes(t *testing.T) {
	shippedByApplication(t)
	testDB.Exec(`INSERT INTO store_coupons (batch_id, face_value, code) VALUES (1, 1000, 'DRAFT-1')`)

	for run := range 2 {
		if err := model.RekeyCouponsByOwner(testDB); err != nil {
			t.Fatalf("run %d: %v", run+1, err)
		}
		if err := testDB.AutoMigrate(&model.Coupon{}, &model.CouponShare{}); err != nil {
			t.Fatalf("run %d: automigrate: %v", run+1, err)
		}
	}
	m := testDB.Migrator()
	if m.HasColumn("store_coupons", "client_id") || !m.HasColumn("store_coupons", "user_id") {
		t.Error("store_coupons must trade client_id for user_id")
	}
	if pk := primaryKey(t, "store_coupon_shares"); len(pk) != 2 || pk[0] != "batch_id" || pk[1] != "user_id" {
		t.Errorf("store_coupon_shares primary key = %v, want [batch_id user_id]", pk)
	}
	var codes []string
	testDB.Raw(`SELECT code FROM store_coupons`).Scan(&codes)
	if len(codes) != 1 || codes[0] != "DRAFT-1" {
		t.Errorf("draft codes = %v, want the one entered before the re-key", codes)
	}
}

func TestRekeyCouponsByOwnerRefusesAnAssignedCoupon(t *testing.T) {
	shippedByApplication(t)
	testDB.Exec(`INSERT INTO store_coupons (batch_id, face_value, code, client_id) VALUES (1, 1000, 'GIVEN-1', 'forum')`)

	if err := model.RekeyCouponsByOwner(testDB); err == nil {
		t.Fatal("an application-keyed allocation must stop the migration")
	}
	if m := testDB.Migrator(); !m.HasColumn("store_coupons", "client_id") || !m.HasColumn("store_coupon_shares", "client_id") {
		t.Error("a refused re-key must leave both tables as they were")
	}
}
