package llmsuggest

import (
	"crypto/sha256"
	"encoding/hex"
	"time"

	"gorm.io/datatypes"
	"gorm.io/gorm"
)

const (
	PromptNamePairV1        = "name-pair-v1"
	PromptNamePairV1B       = "name-pair-v1-batch"
	PromptResidueV1         = "residue-v1"
	PromptBidVerdictV1      = "bid-verdict-v1"
	PromptQueueCreditNameV1 = "queue-creditname-v1"
	PromptWorkPairV1        = "workpair-v1"
	PromptRefV1             = "ref-v1"
	// PromptChainV2 dropped the vndb anchor as a precondition of the EG store
	// chain. Bumping the version is the only way a re-judge reaches the stored
	// rows: upsertJudgement overwrites a stored FAILURE, so re-running the lane
	// against a chain-unproven row writes nothing at all.
	PromptChainV2 = "chain-v2"
	ChainModel    = "rule"
)

const (
	VerdictSame          = "same"
	VerdictDifferent     = "different"
	VerdictUnsure        = "unsure"
	VerdictChainVerified = "chain-verified"
	VerdictChainUnproven = "chain-unproven"
)

const (
	QueueCreditName = "creditname"
	QueueWorkPair   = "workpair"
	QueueRef        = "ref"

	LaneLLM   = "llm"
	LaneChain = "chain"

	FamiliesAll   = "all"
	FamiliesChain = "chain"
	FamiliesLLM   = "llm"
)

type Run struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Task          string         `gorm:"not null" json:"task"`
	Model         string         `gorm:"not null" json:"model"`
	PromptVersion string         `gorm:"not null" json:"prompt_version"`
	Counts        datatypes.JSON `gorm:"type:jsonb" json:"counts"`
	Notes         string         `gorm:"not null;default:''" json:"notes"`
	StartedAt     time.Time      `gorm:"not null" json:"started_at"`
}

func (Run) TableName() string { return "src_llm.run" }

type NamePairJudgment struct {
	ID            int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Task          string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:1" json:"task"`
	InputHash     string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:2" json:"input_hash"`
	Model         string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:3" json:"model"`
	PromptVersion string  `gorm:"not null;uniqueIndex:uq_name_pair,priority:4" json:"prompt_version"`
	A             string  `gorm:"not null" json:"a"`
	B             string  `gorm:"not null" json:"b"`
	GoldLabel     string  `gorm:"not null;default:''" json:"gold_label"`
	SourceRule    string  `gorm:"not null;default:''" json:"source_rule"`
	Verdict       string  `gorm:"not null;default:''" json:"verdict"`
	Reason        string  `gorm:"not null;default:''" json:"reason"`
	Confidence    float64 `gorm:"not null;default:0" json:"confidence"`
	Error         string  `gorm:"not null;default:''" json:"error"`
	CreatedAt     time.Time
}

func (NamePairJudgment) TableName() string { return "src_llm.name_pair_judgment" }

type InfoboxExtraction struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	SrcTable      string         `gorm:"not null" json:"src_table"`
	SrcID         int64          `gorm:"not null" json:"src_id"`
	InputHash     string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:1" json:"input_hash"`
	Model         string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:2" json:"model"`
	PromptVersion string         `gorm:"not null;uniqueIndex:uq_infobox_extraction,priority:3" json:"prompt_version"`
	Extracted     datatypes.JSON `gorm:"type:jsonb" json:"extracted"`
	Error         string         `gorm:"not null;default:''" json:"error"`
	CreatedAt     time.Time
}

func (InfoboxExtraction) TableName() string { return "src_llm.infobox_extraction" }

type BidIdentityVerdict struct {
	ID             int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	WorkID         int64   `gorm:"not null" json:"work_id"`
	GalgameID      int64   `gorm:"not null" json:"galgame_id"`
	BID            int64   `gorm:"column:bid;not null" json:"bid"`
	Layer          string  `gorm:"not null" json:"layer"`
	WikiNames      string  `gorm:"not null;default:''" json:"wiki_names"`
	SubjectNames   string  `gorm:"not null;default:''" json:"subject_names"`
	InputHash      string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:1" json:"input_hash"`
	Model          string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:2" json:"model"`
	PromptVersion  string  `gorm:"not null;uniqueIndex:uq_bid_verdict,priority:3" json:"prompt_version"`
	Verdict        string  `gorm:"not null;default:''" json:"verdict"`
	Reason         string  `gorm:"not null;default:''" json:"reason"`
	Confidence     float64 `gorm:"not null;default:0" json:"confidence"`
	Error          string  `gorm:"not null;default:''" json:"error"`
	CreatedAt      time.Time
	Resolution     string     `gorm:"not null;default:''" json:"resolution"`
	ResolutionNote string     `gorm:"not null;default:''" json:"resolution_note"`
	ResolvedAt     *time.Time `json:"resolved_at"`
}

func (BidIdentityVerdict) TableName() string { return "src_llm.bid_identity_verdict" }

type QueueVerdict struct {
	ID            int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Queue         string         `gorm:"not null;uniqueIndex:uq_queue_verdict,priority:1" json:"queue"`
	EntityType    int16          `gorm:"not null;default:0" json:"entity_type"`
	AID           int64          `gorm:"column:a_id;not null;default:0" json:"a_id"`
	BID           int64          `gorm:"column:b_id;not null;default:0" json:"b_id"`
	EntityID      int64          `gorm:"not null;default:0" json:"entity_id"`
	SourceID      int16          `gorm:"not null;default:0" json:"source_id"`
	ExternalID    string         `gorm:"not null;default:''" json:"external_id"`
	Lane          string         `gorm:"not null" json:"lane"`
	InputHash     string         `gorm:"not null;uniqueIndex:uq_queue_verdict,priority:2" json:"input_hash"`
	Model         string         `gorm:"not null;uniqueIndex:uq_queue_verdict,priority:3" json:"model"`
	PromptVersion string         `gorm:"not null;uniqueIndex:uq_queue_verdict,priority:4" json:"prompt_version"`
	Verdict       string         `gorm:"not null;default:''" json:"verdict"`
	Reason        string         `gorm:"not null;default:''" json:"reason"`
	Confidence    float64        `gorm:"not null;default:0" json:"confidence"`
	Evidence      datatypes.JSON `gorm:"type:jsonb" json:"evidence"`
	Error         string         `gorm:"not null;default:''" json:"error"`
	AppliedAction string         `gorm:"not null;default:''" json:"applied_action"`
	AppliedAt     *time.Time     `json:"applied_at"`
	AppliedBy     *int64         `json:"applied_by"`
	CreatedAt     time.Time
}

func (QueueVerdict) TableName() string { return "src_llm.queue_verdict" }

func EnsureSchema(db *gorm.DB) error {
	if err := db.Exec(`CREATE SCHEMA IF NOT EXISTS src_llm`).Error; err != nil {
		return err
	}
	return db.AutoMigrate(&Run{}, &NamePairJudgment{}, &InfoboxExtraction{}, &BidIdentityVerdict{}, &QueueVerdict{})
}

func hashInput(parts ...string) string {
	h := sha256.New()
	for _, p := range parts {
		h.Write([]byte(p))
		h.Write([]byte{0})
	}
	return hex.EncodeToString(h.Sum(nil))
}
