package model

import (
	"time"

	"gorm.io/datatypes"
)

type App struct {
	ID               int64                       `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ServiceName      string                      `gorm:"uniqueIndex;not null;column:service_name" json:"service_name"`
	DisplayName      string                      `gorm:"not null;column:display_name" json:"display_name"`
	IngestKey        string                      `gorm:"uniqueIndex;not null;column:ingest_key" json:"ingest_key"`
	SymbolsTokenHash *string                     `gorm:"column:symbols_token_hash;uniqueIndex" json:"-"`
	Enabled          bool                        `gorm:"not null;column:enabled" json:"enabled"`
	InAppPrefixes    datatypes.JSONSlice[string] `gorm:"type:jsonb;not null;default:'[]';column:in_app_prefixes" json:"in_app_prefixes"`
	CreatedAt        time.Time                   `gorm:"not null;column:created_at" json:"created_at"`
	UpdatedAt        time.Time                   `gorm:"not null;column:updated_at" json:"updated_at"`
}

func (App) TableName() string { return "telemetry_app" }
