package model

import "time"

type Issue struct {
	ID                int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	AppID             int64     `gorm:"not null;column:app_id;uniqueIndex:idx_telemetry_issue_app_fp,priority:1" json:"app_id"`
	Fingerprint       string    `gorm:"not null;column:fingerprint;uniqueIndex:idx_telemetry_issue_app_fp,priority:2" json:"fingerprint"`
	Kind              string    `gorm:"not null;column:kind" json:"kind"`
	Title             string    `gorm:"not null;column:title" json:"title"`
	Culprit           string    `gorm:"not null;column:culprit" json:"culprit"`
	Status            string    `gorm:"not null;column:status" json:"status"`
	ResolvedInVersion string    `gorm:"not null;column:resolved_in_version" json:"resolved_in_version"`
	Regressed         bool      `gorm:"not null;column:regressed" json:"regressed"`
	FirstSeenDay      time.Time `gorm:"type:date;not null;column:first_seen_day" json:"first_seen_day"`
	LastSeenDay       time.Time `gorm:"type:date;not null;column:last_seen_day" json:"last_seen_day"`
	FirstVersion      string    `gorm:"not null;column:first_version" json:"first_version"`
	LastVersion       string    `gorm:"not null;column:last_version" json:"last_version"`
	CreatedAt         time.Time `gorm:"not null;column:created_at" json:"created_at"`
	UpdatedAt         time.Time `gorm:"not null;column:updated_at" json:"updated_at"`
}

func (Issue) TableName() string { return "telemetry_issue" }

type IssueDaily struct {
	IssueID        int64     `gorm:"primaryKey;column:issue_id" json:"issue_id"`
	Day            time.Time `gorm:"primaryKey;type:date;column:day" json:"day"`
	ServiceVersion string    `gorm:"primaryKey;column:service_version" json:"service_version"`
	Events         int       `gorm:"not null;column:events" json:"events"`
	Sessions       int       `gorm:"not null;column:sessions" json:"sessions"`
}

func (IssueDaily) TableName() string { return "telemetry_issue_daily" }
