package model

import "time"

type SymbolUpload struct {
	ID             int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	AppID          int64     `gorm:"not null;column:app_id" json:"app_id"`
	ServiceVersion string    `gorm:"not null;column:service_version" json:"service_version"`
	EngineRevision string    `gorm:"not null;column:engine_revision" json:"engine_revision"`
	CreatedAt      time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (SymbolUpload) TableName() string { return "telemetry_symbol_upload" }

type SymbolFile struct {
	ID             int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	UploadID       int64     `gorm:"not null;column:upload_id" json:"upload_id"`
	AppID          int64     `gorm:"not null;column:app_id;index:idx_telemetry_symbol_file_app_ver_kind,priority:1" json:"app_id"`
	ServiceVersion string    `gorm:"not null;column:service_version;index:idx_telemetry_symbol_file_app_ver_kind,priority:2" json:"service_version"`
	FileName       string    `gorm:"not null;column:file_name" json:"file_name"`
	Kind           string    `gorm:"not null;column:kind;index:idx_telemetry_symbol_file_app_ver_kind,priority:3" json:"kind"`
	Arch           string    `gorm:"not null;column:arch" json:"arch"`
	BuildID        string    `gorm:"not null;column:build_id;index:idx_telemetry_symbol_file_build_id" json:"build_id"`
	SHA256         string    `gorm:"not null;column:sha256;index:idx_telemetry_symbol_file_sha256" json:"sha256"`
	Size           int64     `gorm:"not null;column:size" json:"size"`
	CreatedAt      time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (SymbolFile) TableName() string { return "telemetry_symbol_file" }

type Blob struct {
	SHA256    string    `gorm:"primaryKey;column:sha256" json:"sha256"`
	Size      int64     `gorm:"not null;column:size" json:"size"`
	CreatedAt time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (Blob) TableName() string { return "telemetry_blob" }

type EngineSymbol struct {
	EngineRevision string    `gorm:"primaryKey;column:engine_revision" json:"engine_revision"`
	Variant        string    `gorm:"primaryKey;column:variant" json:"variant"`
	Status         string    `gorm:"not null;column:status" json:"status"`
	BuildID        string    `gorm:"not null;column:build_id;index:idx_telemetry_engine_symbol_build_id" json:"build_id"`
	SHA256         string    `gorm:"not null;column:sha256" json:"sha256"`
	Size           int64     `gorm:"not null;column:size" json:"size"`
	Attempts       int       `gorm:"not null;column:attempts" json:"attempts"`
	NextAttemptAt  time.Time `gorm:"not null;column:next_attempt_at" json:"next_attempt_at"`
	LastError      string    `gorm:"not null;column:last_error" json:"last_error"`
	UpdatedAt      time.Time `gorm:"not null;column:updated_at" json:"updated_at"`
}

func (EngineSymbol) TableName() string { return "telemetry_engine_symbol" }
