package model

import (
	"regexp"
	"time"

	"gorm.io/datatypes"
)

const (
	NSFWDisplayHide = "hide"
	NSFWDisplayBlur = "blur"
	NSFWDisplayShow = "show"
)

const (
	PreferenceGlobalNamespace = "global"
	PreferenceMaxDocBytes     = 64 * 1024
)

var preferenceNamespacePattern = regexp.MustCompile(`^[a-z0-9_-]{1,64}$`)

func IsNSFWDisplay(v string) bool {
	return v == NSFWDisplayHide || v == NSFWDisplayBlur || v == NSFWDisplayShow
}

func IsPreferenceNamespace(v string) bool {
	return preferenceNamespacePattern.MatchString(v)
}

// EffectiveNSFWDisplay is the rule the deployed downstream sites ship, kept
// verbatim after the 2026-09-23 retirement of the age attestation so none of
// them had to redeploy: adult_confirmed_at is now set on every account, so the
// first branch is simply never taken. The second one still is — an unknown
// nsfw_display is not a display value.
func EffectiveNSFWDisplay(adultConfirmedAt *time.Time, nsfwDisplay string) string {
	if adultConfirmedAt == nil || !IsNSFWDisplay(nsfwDisplay) {
		return NSFWDisplayHide
	}
	return nsfwDisplay
}

type UserPreference struct {
	ID        int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	UserID    uint           `gorm:"not null;uniqueIndex:idx_user_preferences_user_ns,priority:1" json:"user_id"`
	Namespace string         `gorm:"size:64;not null;uniqueIndex:idx_user_preferences_user_ns,priority:2" json:"namespace"`
	Doc       datatypes.JSON `gorm:"type:jsonb;not null;default:'{}'" json:"doc"`
	Version   int            `gorm:"not null" json:"version"`
	CreatedAt time.Time      `json:"created_at"`
	UpdatedAt time.Time      `json:"updated_at"`

	User User `gorm:"foreignKey:UserID;constraint:OnDelete:CASCADE" json:"-"`
}

func (UserPreference) TableName() string {
	return "user_preferences"
}
