package model

import "time"

type CommunityActivity struct {
	ID             int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site           string     `gorm:"not null;uniqueIndex:uq_community_activity_key,priority:1;column:site" json:"site"`
	Key            string     `gorm:"not null;uniqueIndex:uq_community_activity_key,priority:2;column:key" json:"key"`
	ActorID        int64      `gorm:"not null;column:actor_id" json:"actor_id"`
	Verb           int16      `gorm:"not null;column:verb" json:"verb"`
	ObjectKind     string     `gorm:"not null;column:object_kind" json:"object_kind"`
	ObjectLabel    string     `gorm:"not null;column:object_label" json:"object_label"`
	Title          string     `gorm:"not null;column:title" json:"title"`
	Excerpt        string     `gorm:"not null;column:excerpt" json:"excerpt"`
	URL            string     `gorm:"not null;column:url" json:"url"`
	CoverImageHash *string    `gorm:"column:cover_image_hash" json:"cover_image_hash"`
	WorkID         *int64     `gorm:"column:work_id" json:"work_id"`
	ContentLimit   int16      `gorm:"not null;column:content_limit" json:"content_limit"`
	Notify         bool       `gorm:"not null;column:notify" json:"notify"`
	OccurredAt     time.Time  `gorm:"not null;column:occurred_at" json:"occurred_at"`
	BucketDate     time.Time  `gorm:"->;-:migration;column:bucket_date" json:"bucket_date"`
	Revision       int64      `gorm:"not null;column:revision" json:"revision"`
	NotifiedAt     *time.Time `gorm:"column:notified_at" json:"notified_at"`
	RemovedAt      *time.Time `gorm:"column:removed_at" json:"removed_at"`
	CreatedAt      time.Time  `gorm:"not null;column:created_at;autoCreateTime:false" json:"created_at"`
	UpdatedAt      time.Time  `gorm:"not null;column:updated_at;autoUpdateTime:false" json:"updated_at"`
}

func (CommunityActivity) TableName() string { return "community_activity" }

type CommunityActivityGroup struct {
	ID          int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site        string     `gorm:"not null;uniqueIndex:uq_community_activity_group,priority:1;column:site" json:"site"`
	ActorID     int64      `gorm:"not null;uniqueIndex:uq_community_activity_group,priority:2;column:actor_id" json:"actor_id"`
	Verb        int16      `gorm:"not null;uniqueIndex:uq_community_activity_group,priority:3;column:verb" json:"verb"`
	ObjectKind  string     `gorm:"not null;uniqueIndex:uq_community_activity_group,priority:4;column:object_kind" json:"object_kind"`
	BucketDate  time.Time  `gorm:"type:date;not null;uniqueIndex:uq_community_activity_group,priority:5;column:bucket_date" json:"bucket_date"`
	ObjectLabel string     `gorm:"not null;column:object_label" json:"object_label"`
	CountAll    int        `gorm:"not null;column:count_all" json:"count_all"`
	LatestAllID *int64     `gorm:"column:latest_all_id" json:"latest_all_id"`
	LatestAllAt *time.Time `gorm:"column:latest_all_at" json:"latest_all_at"`
	CountSFW    int        `gorm:"not null;column:count_sfw" json:"count_sfw"`
	LatestSFWID *int64     `gorm:"column:latest_sfw_id" json:"latest_sfw_id"`
	LatestSFWAt *time.Time `gorm:"column:latest_sfw_at" json:"latest_sfw_at"`
	CreatedAt   time.Time  `gorm:"not null;column:created_at;autoCreateTime:false" json:"created_at"`
	UpdatedAt   time.Time  `gorm:"not null;column:updated_at;autoUpdateTime:false" json:"updated_at"`
}

func (CommunityActivityGroup) TableName() string { return "community_activity_group" }

type CommunityFeedSeen struct {
	UserID    int64     `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	SeenAt    time.Time `gorm:"not null;column:seen_at" json:"seen_at"`
	UpdatedAt time.Time `gorm:"not null;column:updated_at;autoUpdateTime:false" json:"updated_at"`
}

func (CommunityFeedSeen) TableName() string { return "community_feed_seen" }
