package model

import "time"

type CommunityUserBlock struct {
	ID         int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	BlockerID  int64     `gorm:"not null;uniqueIndex:uq_community_user_block,priority:1;check:chk_community_user_block_self,blocker_id <> blocked_id;column:blocker_id" json:"blocker_id"`
	BlockedID  int64     `gorm:"not null;uniqueIndex:uq_community_user_block,priority:2;column:blocked_id" json:"blocked_id"`
	OriginSite string    `gorm:"not null;column:origin_site" json:"origin_site"`
	CreatedAt  time.Time `gorm:"not null;column:created_at" json:"created_at"`
}

func (CommunityUserBlock) TableName() string { return "community_user_block" }
