package model

import (
	"strconv"
	"time"
)

type CommunityBoard struct {
	ID                 int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site               string    `gorm:"not null;uniqueIndex:uq_community_board_site_slug,priority:1;column:site" json:"site"`
	ParentID           *int64    `gorm:"type:bigint;column:parent_id" json:"parent_id"`
	Slug               string    `gorm:"not null;uniqueIndex:uq_community_board_site_slug,priority:2;column:slug" json:"slug"`
	Name               string    `gorm:"not null;column:name" json:"name"`
	Description        *string   `gorm:"column:description" json:"description"`
	Icon               *string   `gorm:"column:icon" json:"icon"`
	Color              *string   `gorm:"column:color" json:"color"`
	Position           int32     `gorm:"not null;default:0;column:position" json:"position"`
	Format             int16     `gorm:"not null;column:format" json:"format"`
	Status             int16     `gorm:"not null;default:0;column:status" json:"status"`
	ContentRating      int16     `gorm:"not null;default:0;column:content_rating" json:"content_rating"`
	TopicMinTrustLevel int16     `gorm:"not null;default:0;column:topic_min_trust_level" json:"topic_min_trust_level"`
	ReplyMinTrustLevel int16     `gorm:"not null;default:0;column:reply_min_trust_level" json:"reply_min_trust_level"`
	TopicTemplate      *string   `gorm:"column:topic_template" json:"topic_template"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`

	Parent *CommunityBoard `gorm:"foreignKey:ParentID" json:"parent,omitempty"`
}

func (CommunityBoard) TableName() string { return "community_board" }

func BoardAnchorID(boardID int64) string { return strconv.FormatInt(boardID, 10) }

func BoardIDFromAnchor(anchorKind int16, anchorID string) (int64, bool) {
	if anchorKind != AnchorKindBoard {
		return 0, false
	}
	id, err := strconv.ParseInt(anchorID, 10, 64)
	if err != nil || id <= 0 {
		return 0, false
	}
	return id, true
}
