package model

import "time"

type CommunityThreadUser struct {
	ThreadID           int64      `gorm:"primaryKey;autoIncrement:false;column:thread_id" json:"thread_id"`
	UserID             int64      `gorm:"primaryKey;autoIncrement:false;index:idx_community_thread_user_user;column:user_id" json:"user_id"`
	Site               *string    `gorm:"column:site" json:"site"`
	LastReadPostNumber int32      `gorm:"not null;default:0;column:last_read_post_number" json:"last_read_post_number"`
	NotificationLevel  int16      `gorm:"not null;column:notification_level" json:"notification_level"`
	LastVisitedAt      *time.Time `gorm:"column:last_visited_at" json:"last_visited_at"`
}

func (CommunityThreadUser) TableName() string { return "community_thread_user" }

type CommunityAnchorUser struct {
	ID                int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site              string    `gorm:"not null;uniqueIndex:uq_community_anchor_user,priority:1;column:site" json:"site"`
	UserID            int64     `gorm:"not null;uniqueIndex:uq_community_anchor_user,priority:2;column:user_id" json:"user_id"`
	AnchorKind        int16     `gorm:"not null;uniqueIndex:uq_community_anchor_user,priority:3;column:anchor_kind" json:"anchor_kind"`
	AnchorID          string    `gorm:"not null;uniqueIndex:uq_community_anchor_user,priority:4;column:anchor_id" json:"anchor_id"`
	NotificationLevel int16     `gorm:"not null;column:notification_level" json:"notification_level"`
	CreatedAt         time.Time `json:"created_at"`
	UpdatedAt         time.Time `json:"updated_at"`
}

func (CommunityAnchorUser) TableName() string { return "community_anchor_user" }
