package model

import "time"

type CommunityThreadUser struct {
	ThreadID           int64      `gorm:"primaryKey;autoIncrement:false;column:thread_id" json:"thread_id"`
	UserID             int64      `gorm:"primaryKey;autoIncrement:false;index:idx_community_thread_user_user;column:user_id" json:"user_id"`
	LastReadPostNumber int32      `gorm:"not null;default:0;column:last_read_post_number" json:"last_read_post_number"`
	NotificationLevel  int16      `gorm:"not null;column:notification_level" json:"notification_level"`
	LastVisitedAt      *time.Time `gorm:"column:last_visited_at" json:"last_visited_at"`
}

func (CommunityThreadUser) TableName() string { return "community_thread_user" }

type CommunityBoard struct {
	ID          int64   `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site        string  `gorm:"not null;uniqueIndex:uq_community_board_site_slug,priority:1;column:site" json:"site"`
	Name        string  `gorm:"not null;column:name" json:"name"`
	Slug        *string `gorm:"uniqueIndex:uq_community_board_site_slug,priority:2;column:slug" json:"slug"`
	Position    *int32  `gorm:"column:position" json:"position"`
	Description *string `gorm:"column:description" json:"description"`
	Format      int16   `gorm:"not null;column:format" json:"format"`
}

func (CommunityBoard) TableName() string { return "community_board" }
