package model

import "time"

type CommunityUserFollow struct {
	ID         int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	FollowerID int64      `gorm:"not null;uniqueIndex:uq_community_user_follow,priority:1;check:chk_community_user_follow_self,follower_id <> followee_id;column:follower_id" json:"follower_id"`
	FolloweeID int64      `gorm:"not null;uniqueIndex:uq_community_user_follow,priority:2;column:followee_id" json:"followee_id"`
	OriginSite string     `gorm:"not null;column:origin_site" json:"origin_site"`
	CreatedAt  *time.Time `gorm:"column:created_at;autoCreateTime:false" json:"created_at"`
	ImportedAt *time.Time `gorm:"column:imported_at" json:"imported_at"`
}

func (CommunityUserFollow) TableName() string { return "community_user_follow" }
