package model

import (
	"time"

	"gorm.io/datatypes"
)

type CommunityEvent struct {
	ID             int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site           string         `gorm:"not null;column:site" json:"site"`
	Kind           int16          `gorm:"not null;column:kind" json:"kind"`
	ThreadID       int64          `gorm:"not null;column:thread_id" json:"thread_id"`
	PostID         *int64         `gorm:"column:post_id" json:"post_id"`
	ActorID        int64          `gorm:"not null;column:actor_id" json:"actor_id"`
	TargetUserID   *int64         `gorm:"column:target_user_id" json:"target_user_id"`
	MentionUserIDs datatypes.JSON `gorm:"type:jsonb;column:mention_user_ids" json:"mention_user_ids"`
	Attempts       int            `gorm:"not null;default:0;column:attempts" json:"attempts"`
	AttemptAfter   time.Time      `gorm:"not null;column:attempt_after" json:"attempt_after"`
	ProcessedAt    *time.Time     `gorm:"column:processed_at" json:"processed_at"`
	CreatedAt      time.Time      `json:"created_at"`
}

func (CommunityEvent) TableName() string { return "community_event" }

type CommunityNotification struct {
	ID              int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site            string     `gorm:"not null;column:site" json:"site"`
	UserID          int64      `gorm:"not null;column:user_id" json:"user_id"`
	Kind            int16      `gorm:"not null;column:kind" json:"kind"`
	ThreadID        int64      `gorm:"not null;column:thread_id" json:"thread_id"`
	AnchorKind      int16      `gorm:"not null;column:anchor_kind" json:"anchor_kind"`
	AnchorID        string     `gorm:"not null;column:anchor_id" json:"anchor_id"`
	PostID          *int64     `gorm:"column:post_id" json:"post_id"`
	PostNumber      *int32     `gorm:"column:post_number" json:"post_number"`
	FirstPostNumber *int32     `gorm:"column:first_post_number" json:"first_post_number"`
	SinceAt         *time.Time `gorm:"column:since_at" json:"since_at"`
	ActorID         *int64     `gorm:"column:actor_id" json:"actor_id"`
	ActorCount      int        `gorm:"not null;column:actor_count" json:"actor_count"`
	ItemCount       int        `gorm:"not null;column:item_count" json:"item_count"`
	FoldKey         *string    `gorm:"column:fold_key" json:"fold_key"`
	ReadAt          *time.Time `gorm:"column:read_at" json:"read_at"`
	Seq             int64      `gorm:"not null;column:seq" json:"seq"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

func (CommunityNotification) TableName() string { return "community_notification" }
