package model

import (
	"time"

	"gorm.io/datatypes"
)

type CommunityPurgeArchive struct {
	ID         int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site       string         `gorm:"not null;index:idx_community_purge_archive_author,priority:1;column:site" json:"site"`
	AuthorID   int64          `gorm:"not null;index:idx_community_purge_archive_author,priority:2;column:author_id" json:"author_id"`
	Step       string         `gorm:"not null;column:step" json:"step"`
	Data       datatypes.JSON `gorm:"type:jsonb;not null;column:data" json:"data"`
	RestoredAt *time.Time     `gorm:"column:restored_at" json:"restored_at"`
	CreatedAt  time.Time      `gorm:"not null;index:idx_community_purge_archive_created;column:created_at" json:"created_at"`
}

func (CommunityPurgeArchive) TableName() string { return "community_purge_archive" }
