package model

import (
	"time"

	"gorm.io/datatypes"
)

type CommunityThread struct {
	ID                int64          `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site              string         `gorm:"not null;column:site" json:"site"`
	Kind              int16          `gorm:"not null;column:kind" json:"kind"`
	AnchorKind        int16          `gorm:"not null;column:anchor_kind" json:"anchor_kind"`
	AnchorID          string         `gorm:"not null;column:anchor_id" json:"anchor_id"`
	Title             *string        `gorm:"column:title" json:"title"`
	HeaderImageHashes datatypes.JSON `gorm:"type:jsonb;column:header_image_hashes" json:"header_image_hashes"`
	ContentRating     int16          `gorm:"not null;column:content_rating" json:"content_rating"`
	Status            int16          `gorm:"not null;column:status" json:"status"`

	FbStatus      *int16     `gorm:"column:fb_status" json:"fb_status"`
	FbResponse    *string    `gorm:"column:fb_response" json:"fb_response"`
	FbResponderID *int64     `gorm:"column:fb_responder_id" json:"fb_responder_id"`
	FbRespondedAt *time.Time `gorm:"column:fb_responded_at" json:"fb_responded_at"`
	MergedIntoID  *int64     `gorm:"type:bigint;column:merged_into_id" json:"merged_into_id"`
	AnswerPostID  *int64     `gorm:"column:answer_post_id" json:"answer_post_id"`

	PinScope    int16      `gorm:"not null;default:0;column:pin_scope" json:"pin_scope"`
	PinnedAt    *time.Time `gorm:"column:pinned_at" json:"pinned_at"`
	PinnedUntil *time.Time `gorm:"column:pinned_until" json:"pinned_until"`

	PostsCount        int32      `gorm:"not null;default:0;column:posts_count" json:"posts_count"`
	ParticipantsCount int32      `gorm:"not null;default:1;column:participants_count" json:"participants_count"`
	HighestPostNumber int32      `gorm:"not null;default:0;column:highest_post_number" json:"highest_post_number"`
	LastPostedAt      *time.Time `gorm:"column:last_posted_at" json:"last_posted_at"`

	CreatedBy int64     `gorm:"not null;column:created_by" json:"created_by"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`

	MergedInto *CommunityThread `gorm:"foreignKey:MergedIntoID" json:"merged_into,omitempty"`
}

func (CommunityThread) TableName() string { return "community_thread" }

// PinActive is the Go side of repository.pinnedSQL; the two must agree.
func (t *CommunityThread) PinActive(now time.Time) bool {
	return t.PinScope > PinScopeNone && (t.PinnedUntil == nil || t.PinnedUntil.After(now))
}

type CommunityPost struct {
	ID                int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	ThreadID          int64      `gorm:"not null;type:bigint;uniqueIndex:uq_community_post_thread_number,priority:1;index:idx_community_post_thread_root,priority:1;column:thread_id" json:"thread_id"`
	PostNumber        int32      `gorm:"not null;uniqueIndex:uq_community_post_thread_number,priority:2;index:idx_community_post_thread_root,priority:3;column:post_number" json:"post_number"`
	RootPostID        *int64     `gorm:"index:idx_community_post_thread_root,priority:2;column:root_post_id" json:"root_post_id"`
	ReplyToPostID     *int64     `gorm:"column:reply_to_post_id" json:"reply_to_post_id"`
	TargetUserID      *int64     `gorm:"column:target_user_id" json:"target_user_id"`
	AuthorID          int64      `gorm:"not null;column:author_id" json:"author_id"`
	ContentRaw        string     `gorm:"not null;column:content_raw" json:"content_raw"`
	ContentHTML       string     `gorm:"not null;column:content_html" json:"content_html"`
	SanitizerVersion  int32      `gorm:"not null;column:sanitizer_version" json:"sanitizer_version"`
	ContentRating     int16      `gorm:"not null;column:content_rating" json:"content_rating"`
	Status            int16      `gorm:"not null;column:status" json:"status"`
	EditedAt          *time.Time `gorm:"column:edited_at" json:"edited_at"`
	EditedByModerator bool       `gorm:"not null;default:false;column:edited_by_moderator" json:"edited_by_moderator"`
	CreatedAt         time.Time  `json:"created_at"`

	Thread *CommunityThread `gorm:"foreignKey:ThreadID" json:"thread,omitempty"`
}

func (CommunityPost) TableName() string { return "community_post" }

type CommunityReaction struct {
	PostID    int64     `gorm:"primaryKey;autoIncrement:false;column:post_id" json:"post_id"`
	UserID    int64     `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	Kind      int16     `gorm:"primaryKey;autoIncrement:false;column:kind" json:"kind"`
	CreatedAt time.Time `json:"created_at"`
}

func (CommunityReaction) TableName() string { return "community_reaction" }
