package model

import (
	"time"

	"gorm.io/datatypes"
)

type CommunityTrust struct {
	UserID int64 `gorm:"primaryKey;autoIncrement:false;column:user_id" json:"user_id"`
	Level  int16 `gorm:"not null;column:level" json:"level"`

	TopicsEntered  *int32 `gorm:"column:topics_entered" json:"topics_entered"`
	PostsRead      *int32 `gorm:"column:posts_read" json:"posts_read"`
	ReadTimeS      *int32 `gorm:"column:read_time_s" json:"read_time_s"`
	DaysVisited    *int32 `gorm:"column:days_visited" json:"days_visited"`
	LikesGiven     *int32 `gorm:"column:likes_given" json:"likes_given"`
	LikesReceived  *int32 `gorm:"column:likes_received" json:"likes_received"`
	FlagsAgreed    *int32 `gorm:"column:flags_agreed" json:"flags_agreed"`
	FlagsDisagreed *int32 `gorm:"column:flags_disagreed" json:"flags_disagreed"`

	FirstPostsHeldRemaining int32     `gorm:"not null;column:first_posts_held_remaining" json:"first_posts_held_remaining"`
	GrantedBoost            *int16    `gorm:"column:granted_boost" json:"granted_boost"`
	UpdatedAt               time.Time `json:"updated_at"`
}

func (CommunityTrust) TableName() string { return "community_trust" }

type CommunityFlag struct {
	ID        int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	PostID    int64     `gorm:"not null;uniqueIndex:uq_community_flag_post_flagger,priority:1;column:post_id" json:"post_id"`
	FlaggerID int64     `gorm:"not null;uniqueIndex:uq_community_flag_post_flagger,priority:2;column:flagger_id" json:"flagger_id"`
	Reason    *int16    `gorm:"column:reason" json:"reason"`
	Note      *string   `gorm:"column:note" json:"note"`
	Weight    float32   `gorm:"type:real;not null;column:weight" json:"weight"`
	Status    int16     `gorm:"not null;column:status" json:"status"`
	CreatedAt time.Time `json:"created_at"`
}

func (CommunityFlag) TableName() string { return "community_flag" }

type CommunityReviewItem struct {
	ID        int64      `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site      *string    `gorm:"column:site" json:"site"`
	PostID    *int64     `gorm:"column:post_id" json:"post_id"`
	Source    *int16     `gorm:"column:source" json:"source"`
	Status    int16      `gorm:"not null;column:status" json:"status"`
	DecidedBy *int64     `gorm:"column:decided_by" json:"decided_by"`
	DecidedAt *time.Time `gorm:"column:decided_at" json:"decided_at"`
	CreatedAt time.Time  `json:"created_at"`

	TrustReviewItemID *int64     `gorm:"column:trust_review_item_id" json:"trust_review_item_id"`
	ForwardAttempts   int32      `gorm:"not null;default:0;column:forward_attempts" json:"forward_attempts"`
	ForwardAfter      *time.Time `gorm:"column:forward_after" json:"forward_after"`

	MatchedTerms datatypes.JSONSlice[string] `gorm:"type:jsonb;not null;default:'[]';column:matched_terms" json:"matched_terms"`
}

func (CommunityReviewItem) TableName() string { return "community_review_item" }
