package model

import "time"

type CommunityWriteRequest struct {
	ID             int64     `gorm:"primaryKey;autoIncrement:false;type:bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY;default:(-)" json:"id"`
	Site           string    `gorm:"not null;uniqueIndex:uq_community_write_request_key,priority:1;column:site" json:"site"`
	IdempotencyKey string    `gorm:"not null;uniqueIndex:uq_community_write_request_key,priority:2;column:idempotency_key" json:"idempotency_key"`
	RequestHash    string    `gorm:"not null;column:request_hash" json:"request_hash"`
	PostID         *int64    `gorm:"column:post_id" json:"post_id"`
	CreatedAt      time.Time `gorm:"not null;index:idx_community_write_request_created;column:created_at" json:"created_at"`
}

func (CommunityWriteRequest) TableName() string { return "community_write_request" }
